[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "excel-to-markdown"
version = "0.1.0"
authors = [
  { name="Devin Liu", email="devin.r.liu@gmail.com" },
]
description = "A robust Python tool designed to convert Excel files (.xlsx and .xls) into well-formatted Markdown tables."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-only" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=2.2.2",
    "openpyxl>=3.1.5",
    "streamlit>=1.38.0",
    "streamlit-aggrid>=1.0.5",
]

[project.scripts]
excel-to-markdown = "excel_to_markdown.main:main"
app = "run_streamlit:main_app"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-mock>=3.0",
    "build",
    "twine",
    "poetry",
    "ruff>=0.6.0"
]

[tool.setuptools]
py-modules = ["run_streamlit"]
packages = ["excel_to_markdown", "src"]

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501"]
